#!/usr/bin/env sh

SCHEMES_DIR=$HOME/.local/src/iTerm2-Color-Schemes/xrdb
OSC_PATH=$HOME/.local/bin

if [ "$1" = "-all" ]; then
    all=1
    shift
fi

theme="$1"

theme_file=$SCHEMES_DIR/$theme
if [ "$theme" = "dark" ]; then
    #theme_file="$SCHEMES_DIR/Builtin Tango Dark.xrdb"
    #theme_file="$SCHEMES_DIR/synthwave.xrdb"
    theme_file="$SCHEMES_DIR/Jellybeans.xrdb"
fi
if [ "$theme" = "light" ]; then
    #theme_file="$SCHEMES_DIR/Builtin Tango Light.xrdb"
    theme_file="$SCHEMES_DIR/BlulocoLight.xrdb"
    #theme_file="$SCHEMES_DIR/CLRS.xrdb"
    #theme_file="$SCHEMES_DIR/Piatto Light.xrdb"
fi

# finally, set color scheme
#for tty in $(find -E /dev -maxdepth 1 -regex "/dev/ttys[0-9]{3}"); do
if [ $all ]; then
    echo "$theme" > $HOME/.theme
    $OSC_PATH/xrdb2osc.py "$theme_file" $(find -E /dev -maxdepth 1 -regex "/dev/ttys[0-9]{3}")
    #for tty in $(find -E /dev -maxdepth 1 -regex "/dev/ttys[0-9]{3}"); do
    #    $OSC_PATH/xrdb2osc.py "$theme_file" > $tty
    #done
else
    $OSC_PATH/xrdb2osc.py "$theme_file"
fi
