#!/usr/bin/env sh

SCHEMES_DIR=$HOME/.local/src/iTerm2-Color-Schemes
XRDB_DIR=$SCHEMES_DIR/xrdb
KITTY_DIR=$SCHEMES_DIR/kitty
TMUX_DIR=${TMUX_DIR:-$SCHEMES_DIR/tmux}
CONFIG_DIR=$HOME/.config/themes
OSC_PATH=$HOME/.local/bin
KITTY_PATH=/Applications/kitty.app/Contents/MacOS

if [ "$1" = "-all" ]; then
    all=1
    shift
fi

theme="$1"
theme_name="$theme"

#theme_file=$SCHEMES_DIR/$theme
if [ "$theme" = "dark" ]; then
    #theme_file="$SCHEMES_DIR/Builtin Tango Dark.xrdb"
    #theme_file="$SCHEMES_DIR/synthwave.xrdb"
    #theme_file="$SCHEMES_DIR/Jellybeans.xrdb"
    #theme_name=Jellybeans
    # japanesque bad with flux/redshift
    #theme_name=Japanesque
    theme_name=Tomorrow\ Night\ Burns
    TMUX_DIR=${TMUX_DIR}-dark
fi
if [ "$theme" = "light" ]; then
    #theme_file="$SCHEMES_DIR/Builtin Tango Light.xrdb"
    #theme_file="$SCHEMES_DIR/BlulocoLight.xrdb"
    #theme_file="$SCHEMES_DIR/CLRS.xrdb"
    #theme_file="$SCHEMES_DIR/Piatto Light.xrdb"
    #theme_name=BlulocoLight
    theme_name=CLRS
    TMUX_DIR=${TMUX_DIR}-light
fi

# set theme variables
xrdb_file="$XRDB_DIR/${theme_name}.xrdb"
kitty_file="$KITTY_DIR/${theme_name}.colors"
tmux_theme="$TMUX_DIR/${theme_name}.tmux"

# finally, set color scheme
#for tty in $(find -E /dev -maxdepth 1 -regex "/dev/ttys[0-9]{3}"); do
if [ $all ]; then
    echo "$theme" > $HOME/.theme

    # set terminal theme
    #$OSC_PATH/xrdb2osc.py "$xrdb_file" $(find -E /dev -maxdepth 1 -regex "/dev/ttys[0-9]{3}")
    #for tty in $(find -E /dev -maxdepth 1 -regex "/dev/ttys[0-9]{3}"); do
    #    $OSC_PATH/xrdb2osc.py "$theme_file" > $tty
    #done

    # better osc code
    $OSC_PATH/xrdb2osc.sh "$xrdb_file" $(find -E /dev -maxdepth 1 -regex "/dev/ttys[0-9]{3}")

    # use kitty instead of osc codes
    #$KITTY_PATH/kitty @ set-colors -a -c "$kitty_file"

    # set tmux theme
    ln -sf "${tmux_theme}" ${CONFIG_DIR}/theme.tmux
    tmux source-file ${CONFIG_DIR}/theme.tmux
else
    $OSC_PATH/xrdb2osc.sh "$xrdb_file"
    #$KITTY_PATH/kitty @ set-colors "$kitty_file"
fi
